### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(Simdezvous)
add_subdirectory(SimdezvousContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_QtQuick3D_Node15644_Billiards_Stick_Bridge_v2plugin
    Generated_QtQuick3D_Node10477_Satellite_v1_L3plugin
    Simdezvousplugin
    SimdezvousContentplugin)